spring:
  aop:
      auto: true
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/sbdemo?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 10
    minIdle: 1
    maxActive: 20
    maxWait: 30000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j2

mybatis:
  type-aliases-package: com.example.demo.dao.model
  config-location: classpath:spring-mybatis.xml
  mapper-locations: classpath:com/example/demo/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl


pagehelper:
  dialect: com.github.pagehelper.dialect.helper.MySqlDialect
security:
  basic:
    path: /swagger-ui.html
    enabled: true
  user:
    name: demo
    password: demo


